### ISSUE TITLE
Indentation in YAML file to set accessTokenMaxAgeSeconds in disconnected-usage is wrong

### ISSUE THREAD

**Issue by JoachimGross** [ibm-cloud-docs/satellite#28]
In [High Availability, Disaster Recovery, and Disconnected Usage](https://cloud.ibm.com/docs/satellite?topic=satellite-ha) in the last chapter [Disconnected Usage](https://cloud.ibm.com/docs/satellite?topic=satellite-ha#disconnected-usage) the indentation of the yaml file shown to change the `accessTokenMaxAgeSeconds` is wrong.

If I copy and paste the file and try to apply it I get an error.

```
# cat DisconnectedUsage.yaml

apiVersion: config.openshift.io/v1
kind: OAuth
  metadata:
    name: cluster
  spec:
    tokenConfig:
      accessTokenMaxAgeSeconds: 259200

# oc apply -f DisconnectedUsage.yaml
error: error parsing DisconnectedUsage.yaml: error converting YAML to JSON: yaml: line 3: mapping values are not allowed in this context
```

The correct file is 

```
# cat accessTokenMaxAgeSeconds-72h.yaml

apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  tokenConfig:
    accessTokenMaxAgeSeconds: 259200

# oc apply -f accessTokenMaxAgeSeconds-72h.yaml
oauth.config.openshift.io/cluster configured
```

Can you please correct this.
